# Site settings
title: Stellar Machine
email: Dave.morgan@stellarmachine.com
description: > # this means to ignore newlines until "baseurl:" This will be the description for Stellar Machine.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stellar-machine.netlify.com/" # the base hostname & protocol for your site
github_username:  russ3llc

# Build settings
markdown: kramdown
